#!/usr/bin/env bash

# Check if Java is installed.
(hash java 2>/dev/null && hash javac 2>/dev/null) || {
	echo >&2 "[!] J depends on Java (java and javac) to compile and then run the \"scripts\".";
	exit 1;
}

help_msg() {
  >&$1 echo "J: Compile and Execute Java \"Scripts\" in One Go!"
	>&$1 echo "Usage: j file.java [program arguments]"
  >&$1 echo
  >&$1 echo "  $ j Sudoku.java"
  >&$1 echo "  $ j Sudoku.java Jack Jill"
  >&$1 echo
}

cleanup() {
	rm -rf "*.class"
}

# Help to display if we have no arguments and no stdin.
if [[ $# -eq 0 && -t 0 ]]; then
  help_msg 2
  exit 1
fi

# Help to display if we get the flags.
if [[ "$1" == "--help" || "$1" == "-h" ]]; then
  help_msg 1
  exit 0
fi

# Ensure specified Java "script" exists.
if [[ ! -e $1 ]]; then
	echo >&2 "[!] I can't find that file ($1)!";
	exit 1;
fi

# Compile the file.
javac $1

# Run the "script". Assume the file ends in ".java".
if [[ $# < 2 ]]; then
	java "${1%.java}"
else
	java "${1%.java}" "${@:2}"
fi
